version: '2'
services:

  nlgserv:
    build:
      context: .
      dockerfile: ./nlgserv/Dockerfile
    ports: ["8000:8000"] # HOST:CONTAINER

  writer:
    build:
      context: .
      dockerfile: ./writer/Dockerfile
    env_file: .env
    ports: ["5000:5000"] # HOST:CONTAINER
    links:
      - nlgserv

  writer2:
    build:
      context: .
      dockerfile: ./writer2/Dockerfile
    env_file: .env

  writer3:
    build:
      context: .
      dockerfile: ./writer3/Dockerfile
    env_file: .env